# Simple Task which runs inside a container of base ubuntu image
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  steps:
    - name: goodbye
      image: ubuntu
      command:
        - echo
      args:
        - "Bye!"